[package]
name = "asteroids_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.14.2"
tracing-subscriber = "0.3.19"
tracing-log = "0.2.0"
tracing = "0.1.41"
avian2d = "0.1.2"
rand = "0.8"
